
services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
      - '8080:8080'
      - '4001:4001'
    command: ["daemon", "--init", "--migrate=true"]
    volumes:
      - ./data/ipfs:/data/ipfs

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_USER: graph-node
      POSTGRES_DB: graph-node
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  graph-node:
    image: graphprotocol/graph-node:v0.27.0
    ports:
      - '8000:8000'  # GraphQL
      - '8001:8001'  # WebSocket
      - '8020:8020'  # Admin API
      - '8030:8030'  # Metrics
      - '8040:8040'  # Status
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: letmein
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'ws://127.0.0.1:8545'
      RUST_LOG: info
    depends_on:
      - postgres
      - ipfs
