# This file is for DEVELOPMENT with HOT-RELOADING

services:
  # --- 1. BLOCKCHAIN (UNCHANGED) ---
  hardhat-node:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    ports:
      - '8545:8545'
    volumes:
      - ./hardhat/scripts:/app/scripts
      - ./hardhat/deployment-addresses.json:/app/deployment-addresses.json

  # --- 2. FRONTEND (MODIFIED FOR DEV) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # <-- USES NEW DOCKERFILE
    ports:
      - '5173:5173' # <-- EXPOSES VITE DEV PORT
    volumes:
      # This syncs your local code for hot-reloading
      - ./frontend:/app
      # This prevents your local node_modules from overwriting the container's
      - /app/node_modules
    depends_on:
      - graph-node

  # --- 3. GRAPHQL (UNCHANGED) ---
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
      - '8080:8080'
    command: ["daemon", "--init", "--migrate=true"]
    volumes:
      - ./data/ipfs:/data/ipfs

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: letmein
      POSTGRES_USER: graph-node
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
      LC_ALL: C
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: 
      - "postgres"
      - "-cshared_preload_libraries=pg_stat_statements"
      - "-clisten_addresses=*"

  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: letmein
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'local:http://hardhat-node:8545'
      GRAPH_LOG: info
    depends_on:
      - postgres
      - ipfs
      - hardhat-node